spring:
  datasource:
      url: jdbc:mysql://localhost:3306/hope?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml

server:
  port: 9090
  servlet:
    context-path: /
