# 项目相关配置
project:
  # 名称
  name: engine
  # 版本
  version: 2.2.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/engine/uploadPath，Linux配置 /home/engine/uploadPath）
  profile: D:/engine/uploadPath
  # 获取ip地址开关
  addressEnabled: true

spring:
  datasource:
    url: jdbc:mysql://10.134.6.32:3306/hope?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  ###########################redis#########################
  #Redis数据库索引（默认为0）
  redis:
    database: 0
    #Redis服务器地址
    #host: 127.0.0.1
    host: 10.128.134.101
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: 123456
    #连接池最大连接数（使用负值表示没有限制）
    jedis.pool.max-active: 10
    #连接池最大阻塞等待时间（使用负值表示没有限制）
    jedis.pool.max-wait: -1
    #连接池中的最大空闲连接
    jedis.pool.max-idle: 8
    #连接池中的最小空闲连接
    jedis.pool.min-idle: 0
    #连接超时时间（毫秒）
    timeout: 1000

mybatis:
  mapperLocations: classpath:/mapper/*.xml

server:
  port: 9090
  servlet:
    context-path: /


